// server/api/winball-config.get.js
import { defineEventHandler } from 'h3'
import { prisma as db } from '@/server/prisma'

const DEFAULTS = {
  // Colors
  winballColorBackground: '#ffffff',
  winballColorBackboard:  '#F0E6FF',
  winballColorWalls:      '#4b4b4b',
  winballColorBall:       '#ff0000',
  winballColorBumpers:    '#8c8cff',
  winballColorLeftCup:    '#8c8cff',
  winballColorRightCup:   '#8c8cff',
  winballColorGoldCup:    '#FFD700',
  winballColorCap:        '#ffd000',
  winballColorTransform:  '#ffffff',
  winballColorTransformIntensity: 0,
  winballOverlayColor:    '#ffffff',
  winballOverlayAlpha:    0,
  winballImageWidthPercent: 100,
  winballImageOffsetXPercent: 0,
  winballImageOffsetYPercent: 0,
  winballBackboardImagePath: null,
  winballBumper1ImagePath:   null,
  winballBumper2ImagePath:   null,
  winballBumper3ImagePath:   null,
  // Bumper geometry
  winballBumper1Radius: 6,
  winballBumper1Height: 6,
  winballBumper1X:      -8,
  winballBumper1Z:      -9,
  winballBumper2Radius: 6,
  winballBumper2Height: 6,
  winballBumper2X:      -1,
  winballBumper2Z:      0,
  winballBumper3Radius: 6,
  winballBumper3Height: 6,
  winballBumper3X:      6,
  winballBumper3Z:      -9,
  // Triangle geometry
  winballTriangle1Radius: 6,
  winballTriangle1Depth:  6,
  winballTriangle1X:      -15,
  winballTriangle1Z:      -2,
  winballTriangle2Radius: 0,
  winballTriangle2Depth:  6,
  winballTriangle2X:      15,
  winballTriangle2Z:      -2,
  winballTriangle3Radius: 4,
  winballTriangle3Depth:  6,
  winballTriangle3X:      13,
  winballTriangle3Z:      -2,
  // Peg geometry
  winballPeg1Radius:  0.5, winballPeg1Height:  4, winballPeg1X:  -11, winballPeg1Z:  -17,
  winballPeg2Radius:  0.5, winballPeg2Height:  4, winballPeg2X:   -3, winballPeg2Z:  -17,
  winballPeg3Radius:  0.5, winballPeg3Height:  4, winballPeg3X:    5, winballPeg3Z:  -17,
  winballPeg4Radius:  0.5, winballPeg4Height:  4, winballPeg4X:   12, winballPeg4Z:  -17,
  winballPeg5Radius:  0.5, winballPeg5Height:  4, winballPeg5X:  -12, winballPeg5Z:   -6,
  winballPeg6Radius:  0.5, winballPeg6Height:  4, winballPeg6X:   -5, winballPeg6Z:   -6,
  winballPeg7Radius:  0.5, winballPeg7Height:  4, winballPeg7X:    2, winballPeg7Z:   -6,
  winballPeg8Radius:  0.5, winballPeg8Height:  4, winballPeg8X:   10, winballPeg8Z:   -6,
  winballPeg9Radius:  0.5, winballPeg9Height:  4, winballPeg9X:  -12, winballPeg9Z:    4,
  winballPeg10Radius: 0.5, winballPeg10Height: 4, winballPeg10X:  -5, winballPeg10Z:   5,
  winballPeg11Radius: 0.5, winballPeg11Height: 4, winballPeg11X:   3, winballPeg11Z:   4,
  winballPeg12Radius: 0.5, winballPeg12Height: 4, winballPeg12X:  11, winballPeg12Z:   4,
  // Physics
  winballGravity:             15,
  winballBallMass:            8,
  winballBallLinearDamping:   0.2,
  winballBallAngularDamping:  0,
  winballBallWallRestitution: 1.2,
  winballPlungerMaxPull:      0.6,
  winballPlungerImpactFactor: 0.2,
  winballPlungerForce:        500
}

export default defineEventHandler(async () => {
  const config = await db.gameConfig.findUnique({
    where: { gameName: 'Winball' },
    select: {
      winballColorBackground:     true,
      winballColorBackboard:      true,
      winballColorWalls:          true,
      winballColorBall:           true,
      winballColorBumpers:        true,
      winballColorLeftCup:        true,
      winballColorRightCup:       true,
      winballColorGoldCup:        true,
      winballColorCap:            true,
      winballColorTransform:      true,
      winballColorTransformIntensity: true,
      winballOverlayColor:        true,
      winballOverlayAlpha:        true,
      winballImageWidthPercent:   true,
      winballImageOffsetXPercent: true,
      winballImageOffsetYPercent: true,
      winballBackboardImagePath:  true,
      winballBumper1ImagePath:    true,
      winballBumper2ImagePath:    true,
      winballBumper3ImagePath:    true,
      winballBumper1Radius:       true,
      winballBumper1Height:       true,
      winballBumper1X:            true,
      winballBumper1Z:            true,
      winballBumper2Radius:       true,
      winballBumper2Height:       true,
      winballBumper2X:            true,
      winballBumper2Z:            true,
      winballBumper3Radius:       true,
      winballBumper3Height:       true,
      winballBumper3X:            true,
      winballBumper3Z:            true,
      winballTriangle1Radius:     true,
      winballTriangle1Depth:      true,
      winballTriangle1X:          true,
      winballTriangle1Z:          true,
      winballTriangle2Radius:     true,
      winballTriangle2Depth:      true,
      winballTriangle2X:          true,
      winballTriangle2Z:          true,
      winballTriangle3Radius:     true,
      winballTriangle3Depth:      true,
      winballTriangle3X:          true,
      winballTriangle3Z:          true,
      winballPeg1Radius:  true, winballPeg1Height:  true, winballPeg1X:  true, winballPeg1Z:  true,
      winballPeg2Radius:  true, winballPeg2Height:  true, winballPeg2X:  true, winballPeg2Z:  true,
      winballPeg3Radius:  true, winballPeg3Height:  true, winballPeg3X:  true, winballPeg3Z:  true,
      winballPeg4Radius:  true, winballPeg4Height:  true, winballPeg4X:  true, winballPeg4Z:  true,
      winballPeg5Radius:  true, winballPeg5Height:  true, winballPeg5X:  true, winballPeg5Z:  true,
      winballPeg6Radius:  true, winballPeg6Height:  true, winballPeg6X:  true, winballPeg6Z:  true,
      winballPeg7Radius:  true, winballPeg7Height:  true, winballPeg7X:  true, winballPeg7Z:  true,
      winballPeg8Radius:  true, winballPeg8Height:  true, winballPeg8X:  true, winballPeg8Z:  true,
      winballPeg9Radius:  true, winballPeg9Height:  true, winballPeg9X:  true, winballPeg9Z:  true,
      winballPeg10Radius: true, winballPeg10Height: true, winballPeg10X: true, winballPeg10Z: true,
      winballPeg11Radius: true, winballPeg11Height: true, winballPeg11X: true, winballPeg11Z: true,
      winballPeg12Radius: true, winballPeg12Height: true, winballPeg12X: true, winballPeg12Z: true,
      winballGravity:             true,
      winballBallMass:            true,
      winballBallLinearDamping:   true,
      winballBallAngularDamping:  true,
      winballBallWallRestitution: true,
      winballPlungerMaxPull:      true,
      winballPlungerImpactFactor: true,
      winballPlungerForce:        true
    }
  })

  // Merge db values over defaults so null/missing fields fall back to defaults
  return { ...DEFAULTS, ...Object.fromEntries(
    Object.entries(config || {}).filter(([, v]) => v != null)
  )}
})
