-- AlterEnum
ALTER TYPE "CMoonEffectType" ADD VALUE 'SLIME_FLOOD';
ALTER TYPE "CMoonEffectType" ADD VALUE 'SNAKE';
ALTER TYPE "CMoonEffectType" ADD VALUE 'TEXT_CALLOUT';
ALTER TYPE "CMoonEffectType" ADD VALUE 'POKEBALL';
ALTER TYPE "CMoonEffectType" ADD VALUE 'FIREWORKS';
