-- CreateTable
CREATE TABLE "UserIP" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "ipAddress" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserIP_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "UserIP" ADD CONSTRAINT "UserIP_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
