// server/utils/tutorialDefaultContent.js
// Fallback copy shown until an admin saves their own text for a section
// (server/api/tutorial/index.get.js merges these in per-key so the page
// never ships blank, while still being fully overridable in admin).
export const DEFAULT_SECTIONS = {
  intro: '<p>Welcome to Cartoon ReOrbit! This guide walks new players through everything you can do on the site &mdash; collecting cToons, earning points, trading with other players, and more. Bookmark this page any time you need a refresher.</p>',
  auctions: '<p>The Auction House lets you list a cToon you own for other players to bid on. Set a starting bid and a duration, then watch the offers roll in &mdash; you can even set up an auto-bid on someone else&rsquo;s auction so the system bids for you up to a limit you choose. When time runs out, the highest bidder wins and the cToon is instantly transferred to their collection.</p>',
  trades: '<p>Trading is how players swap cToons and points directly with each other. From the Trade page, browse your Incoming and Outgoing offers, or start a new one by picking any combination of cToons and points to offer another player. They can accept, reject, or send back a counter-offer, so feel free to negotiate until you&rsquo;re both happy with the deal.</p>',
  cmoons: '<p>cMoons are the site&rsquo;s player factions &mdash; pick a team shortly after joining and represent it in a weekly leaderboard race against every other cMoon. Your team earns points when members play games, complete daily tasks, and win battles, so your activity helps your cMoon climb the ranks. Visit your cMoon&rsquo;s page any time to see its roster and rank standings.</p>',
  cmart: '<p>cMart is the site&rsquo;s shop, where you spend points on blind booster Packs containing randomized cToons, or grab cToons directly from time-limited Sales. Opening a pack is a fun surprise &mdash; watch the reveal animation to see what you pulled! Check back regularly, since Sales rotate and sell out.</p>',
  games: '<p>The Games hub links to more than a dozen mini-games &mdash; everything from Winball and the Win Wheel to Lotto, Blackjack, Memory, Tower Stack, and several themed arcade games. Playing games is one of the best ways to earn points, and your best scores count toward the site&rsquo;s leaderboards.</p>',
  cworld: '<p>My cWorld is your personal hub &mdash; from here you can reach My cZone (your own customizable profile room where you arrange and show off your cToon collection), your full Collection, the master list of All cToons, your Achievements, and your Wishlist. Other players can visit your cZone, so it&rsquo;s worth decorating.</p>',
  points: '<p>Points are the currency you&rsquo;ll use throughout the site, mainly to buy packs and cToons in cMart. You earn points just by logging in each day, and brand-new players get an even bigger bonus during their first week &mdash; see the numbers below.</p><p>Beyond your daily login bonus, you can earn more points by visiting other players&rsquo; cZones, playing games, unlocking achievements, winning the daily lotto, and redeeming codes shared by the team.</p><p>cMoons also track their own separate team-score tasks, which help your faction&rsquo;s weekly leaderboard rank &mdash; that&rsquo;s different from your personal point balance above.</p>',
  tips: '<ul><li>Check cMart daily since Sales rotate and don&rsquo;t come back.</li><li>Log in every day during your first week to make the most of the new-player point bonus.</li><li>Visit other players&rsquo; cZones for quick points and inspiration for decorating your own.</li><li>Join a cMoon early so you don&rsquo;t miss out on team leaderboard progress.</li><li>Explore &mdash; there&rsquo;s a lot to discover on Cartoon ReOrbit!</li></ul>'
}
